server:
  port: 8099
spring:
  main:
    banner-mode: off


mydata:
  mysql:
    url-write: jdbc:mysql://127.0.0.1:3316/performance?useUnicode=true&characterEncoding=utf8&useSSL=false
    url-read01: jdbc:mysql://127.0.0.1:3326/performance?useUnicode=true&characterEncoding=utf8&useSSL=false
    url-read02: jdbc:mysql://127.0.0.1:3336/performance?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: performance
    password: performance^pw

