spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9001,localhost:9002,localhost:9003
    consumer:
      # ????????
      max-poll-records: 10
      # ??????????
      auto-offset-reset: latest
      # ??????????????????????????????? 1MB
      max-partition-fetch-bytes: 1024000

server:
  port: 8181

mydata:
  kafka:
    producer-topic: test32
